### PR TITLE
Kmedoids dijkstra clustering

### PR DESCRIPTION
**Pull request by KathiEsterl**
Implementation for k-medoids Dijkstra Clustering; added interim solutions for spatial clustering

see #336

### CODE REVIEW

**Comment by ulfmueller** [comment]
Started checking this. I ran into the problem that this 0e331705652c21b1d2ac12a66b831622c62abeda apparently is not implemented. After that I got an error in set_line_costs... I think it is worth pulling from dev and creating a 'clean and up-to-date' development. @KathiEsterl could you do so? Once it works with the current dev merged and with the current data I would then test it... Or do you think somewhat differently? Do I have to use some old data?

**Comment by ulfmueller** [comment]
ahh sorry, you probably pulled from [this branch](https://github.com/openego/eTraGo/tree/features/%23344-update-adjust-network) to get it mostly running.... I guess we should deal with that PR first.... Give me some more time for testing and then I might come back to you...

**Comment by KathiEsterl** [comment]
Sorry I haven't answered yet. 
I created this kmedoids-dijkstra-branch from the dev branch before this has been adapted to the new datasets. That is why I also had to add a interim solution for the spatial clustering, but the k-medoids Dijkstra algortihm should be working. 
I kind of lost track what has been adapted since then, so I am sorry to say I probably can't help you with the meanwhile changes and differences to the current dev. 
However, if you think it would be better to start off with a new branch and implement it there, I could do that. I think, it wouldn't take much time - there only have been some problems last time, because the ehv-clustering and other stuff haven't been working, but that should be fine now. 
Just let me know if you can't get it running.

**Comment by ulfmueller** [comment]
The dev is now 'up-to-date'. @KathiEsterl dont you think you can update this branch by merging dev into it? I think you know best, what shall be kept at your side and what comes in from dev and where there should be any adjustments to your code (at best there is none)....

**Comment by KathiEsterl** [comment]
I merged the dev into this branch now. When testing it, I run into errors. I suppose those come from incompatibility to the new data with the new sectors, but I will have a deeper look into it and let you know.

**Comment by KathiEsterl** [comment]
Okay, I added some interim solutions to be able to test it with a backup of the SH-Testcase data I got from @ClaraBuettner and to exclude data from other sectors as it still needs to be adapted to other sectors. Those are marked with a **# TODO**, you find them [here](https://github.com/openego/eTraGo/blob/ec35e04c9988e52a7990273b4d0d486cbfcdd259/etrago/appl.py#L348) and [here](https://github.com/openego/eTraGo/blob/ec35e04c9988e52a7990273b4d0d486cbfcdd259/etrago/cluster/networkclustering.py#L913). 

Unfortunately I am still running into an error in the part of the aggregation the clusters. It must be a new one, I looked up my notes from back then where I documented the problems I had before. I think it must have to do something with compatibility of new versions or new data or something. Maybe you can try and have a look on it, if you run into this error aswell? Thank you! 

> The dev is now 'up-to-date'. @KathiEsterl dont you think you can update this branch by merging dev into it? I think you know best, what shall be kept at your side and what comes in from dev and where there should be any adjustments to your code (at best there is none)....

**Comment by ulfmueller** [comment]
Thx! Yes, I am testing it and I run into a KeyError: 'country' in the geolocation_buses function. Skipping that function makes the clustering go through til the end. I guess it is not really needed for the clustering and basically a nice-to-have to have country tags on the lines and links. I dont get that error though, when I debug it with pdb it does not occur. :man_shrugging:

**Comment by ulfmueller** [comment]
@KathiEsterl do you go for it? Or should I try to get a clue about it?

**Comment by ulfmueller** [comment]
And how do we tackle the fact that it does not work so far in combination with the other sectors. I think it would make sense to include this development into [this one](https://github.com/openego/eTraGo/tree/features/%23333_spatial_clustering_for_sector_coupling) @CarlosEpia (and @KathiEsterl  ) do you think it'll be easy to make sure that the k-medoids clustering also works for the other sectors? If yes, 'someone' could merge that spatial clustering for sector coupling branch into this one and we could get rid of the work-arounds done by @KathiEsterl

**Comment by KathiEsterl** [comment]
> Thx! Yes, I am testing it and I run into a KeyError: 'country' in the geolocation_buses function. Skipping that function makes the clustering go through til the end. I guess it is not really needed for the clustering and basically a nice-to-have to have country tags on the lines and links. I dont get that error though, when I debug it with pdb it does not occur. man_shrugging

I think I know this error ('country' in the geolocation_buses function) from using old datasets, but I didn't run into it anymore using the up-to-date dataset backup by Clara.
Do you think we should still just remove this function there? I can do that, if you think so. 

But, if I get you right, so you dont run into this error I am getting (something in pypsa concerning the aggregation of the clusters)? Well, then I guess it is just something about the dataset or some version I am using...

**Comment by KathiEsterl** [comment]
> And how do we tackle the fact that it does not work so far in combination with the other sectors? I think it would make sense to include this development into [this one](https://github.com/openego/eTraGo/tree/features/%23333_spatial_clustering_for_sector_coupling). @CarlosEpia (and @KathiEsterl ) do you think it'll be easy to make sure that the k-medoids clustering also works for the other sectors? If yes, 'someone' could merge that 'spatial clustering for sector coupling branch' into this one and we could get rid of the work-arounds done by @KathiEsterl

I think, if there is a solution for the k-means Clustering, we can probably adapt the k-medoids Dijkstra Clustering accordingly quite easily. I don't know how it is done for the k-means Clustering, but in the end, the k-medoids Dijkstra Clustering is implemented very similar, so I guess this won't be a problem. 

What do you think, @CarlosEpia ? If you need some more information concerning the k-medoids Dijkstra Clustering, just let me know.

**Comment by CarlosEpia** [comment]
I think it is a good idea to merge the branches 337 and 333 to check if they are working correctly together as @ulfmueller suggested. @KathiEsterl can I have a copy of the up-to-date dataset that you mentioned? I'm also running into the error about the "country" column.

**Comment by KathiEsterl** [comment]
> I think it is a good idea to merge the branches 337 and 333 to check if they are working correctly together as @ulfmueller suggested. @KathiEsterl can I have a copy of the up-to-date dataset that you mentioned? I'm also running into the error about the "country" column.

I will send you the link per e-mail.

**Comment by CarlosEpia** [comment]
Received. Thanks Kathi!

**Comment by ulfmueller** [comment]
Hi you two! just to know what comes next: who of you will be merging the two developments? @CarlosEpia will you do so? Let me know if I can help - otherwise I would expect a combined PR within the next days which I could test and review...

**Comment by CarlosEpia** [comment]
Hi Ulf! If @KathiEsterl agrees, I will take care of it this week.

**Comment by ulfmueller** [comment]
As I read it, she already agreed :wink:

**Comment by KathiEsterl** [comment]
Yes, I agree! Thank you, Carlos! 
Let me know if I can help with something.

**Comment by KathiEsterl** [comment]
This problem is solved in #379 .

**Pull request closed without merging**
