### PR TITLE
improve topology in Munich

### PR DESCRIPTION
**Pull request by jankaeh**

### CODE REVIEW

**Comment by ulfmueller** [comment]
I will check your approach once our new data release 0.4.2 is finished and see how we can combine it with #31 This will happen the latest by the end of July.

**Comment by lukasoldi** [comment]
I tried applying your approach, but got this error. Any clues on that?

> ~/eTraGo/etrago/appl.py in etrago(args)
>     313 
> --> 314     add_missing_components(network)
>     315 
>     316     # grouping of parallel lines
> 
> ~/eTraGo/etrago/tools/utilities.py in add_missing_components(network)
>     360      ) = (from_shape(MultiLineString
>     361                      ([LineString([wkb.loads(network.buses.geom['23648'],
> --> 362                                              hex=True),
>     363                                    wkb.loads(network.buses.geom['16573'],
>     364                                              hex=True)])]), 4326))
> 
> ~/lukas_ego/lib/python3.5/site-packages/shapely/wkb.py in loads(data, hex)
>      12     reader = geos.WKBReader(geos.lgeos)
>      13     if hex:
> ---> 14         return reader.read_hex(data)
>      15     else:
>      16         return reader.read(data)
> 
> ~/lukas_ego/lib/python3.5/site-packages/shapely/geos.py in read_hex(self, data)
>     404             data = data.encode('ascii')
>     405         geom = self._lgeos.GEOSWKBReader_readHEX(
> --> 406             self._reader, c_char_p(data), c_size_t(len(data)))
>     407         if not geom:
>     408             raise WKBReadingError(
> 
> TypeError: bytes or integer address expected instead of Function instance`
>

**Comment by jankaeh** [comment]
Works on my system, but historically grown I don't use an entire installation of etrago, so I cannot really compare. Maybe you can just adopt the line from the function data_manipulation_sh, which should do the same without using wkb.loads, which did not work on my system though:
instead of:
from_shape(MultiLineString([LineString([wkb.loads(network.buses.geom['23648'],hex=True),wkb.loads(network.buses.geom['16573'],hex=True)])]), 4326))
it would be:
from_shape(MultiLineString([LineString([to_shape(network.buses.geom['23648']),to_shape(network.buses.geom['16573'])])]),4326))

same for topo and again at line 408-419

**Comment by lukasoldi** [comment]
I have changed your function to comply with the full etrago set, see https://github.com/openego/eTraGo/commit/210a5d5b2a7d8802d0212d0a22d06af5e402a9fc

@jankaeh how did your result improve/change with the changes in place? In my case there is only a very slight change in results.

**Comment by ulfmueller** [comment]
The adapted function is also part of the branch feature/test_powerflow which will be merged into dev soon. So I close this PR for now. 
Btw: Our experience was similar to @lukasoldi. Also when calculating the PF, our problems were coming from bugs and the abstract modelling of the neighboring countries instead these topology changes had a rather small impact. The PF is converging also without these changes. Anyhow the function will be included and can be used if one desires. Thx again @jankaeh for sharing your work!

**Pull request closed without merging**
