### PR TITLE
update plot_clusters to also account for gas pipelines

### PR DESCRIPTION
**Pull request by pieterhexen**
Hey @CarlosEpia,
I updated plot_clusters by adding the option to plot the disaggregated CH4 pipelines. The paramaters and their default values have been updated to avoid problems accruing when plotting CH4 clusters without explicitly setting the transmission_lines to False.

Most of the file changes are originating from black. Only lines 2032 to 2037 add functionality.

### CODE REVIEW

**Comment by CarlosEpia** [comment]
Hi Pieter. There was another pull request that modifies this function that was just merged into dev. Could you please merge dev into this branch and change the required lines before I test it? You can find more details in #518

**Comment by pieterhexen** [comment]
> Hi Pieter. There was another pull request that modifies this function that was just merged into dev. Could you please merge dev into this branch and change the required lines before I test it? You can find more details in #518

Done :)

**Comment by CarlosEpia** [comment]
I just tested this branch and it works nicely, but the option gas_pipelines = True does not work when you import the etrago object. I suppose that your problem can be solved in the same way that I did in the next lines: https://github.com/openego/eTraGo/blob/edce42e6f2843edf8d2e7affa9d9579f0085458d/etrago/tools/plot.py#L2015-L2022


  File "/tmp/ipykernel_23335/3170384549.py", line 1, in <cell line: 1>
    etrago2.plot_clusters(gas_pipelines=True)

  File "/home/student/git/eTraGo/etrago/tools/plot.py", line 2051, in plot_clusters
    pipelines = gpd.GeoDataFrame(pipelines, geometry="geom")

  File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/geodataframe.py", line 188, in __init__
    self.set_geometry(geometry, inplace=True, crs=crs)

  File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/geodataframe.py", line 346, in set_geometry
    level = _ensure_geometry(level, crs=crs)

  File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/geodataframe.py", line 59, in _ensure_geometry
    out = from_shapely(np.asarray(data), crs=crs)

  File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/array.py", line 154, in from_shapely
    return GeometryArray(vectorized.from_shapely(data), crs=crs)

  File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/_vectorized.py", line 145, in from_shapely
    raise TypeError("Input must be valid geometry objects: {0}".format(geom))

TypeError: Input must be valid geometry objects: MULTILINESTRING ((9.285375 54.803584, 9.29062 54.64853), (9.29062 54.64853, 9.295828 54.49347), (9.295828 54.49347, 9.326504 54.45439), (9.326504 54.45439, 9.315207 54.381631), (9.315207 54.381631, 9.422704 54.264688), (9.422704 54.264688, 9.369836 54.153612))

**Comment by pieterhexen** [comment]
> I just tested this branch and it works nicely, but the option gas_pipelines = True does not work when you import the etrago object. I suppose that your problem can be solved in the same way that I did in the next lines:
> 
> https://github.com/openego/eTraGo/blob/edce42e6f2843edf8d2e7affa9d9579f0085458d/etrago/tools/plot.py#L2015-L2022
> 
> File "/tmp/ipykernel_23335/3170384549.py", line 1, in <cell line: 1> etrago2.plot_clusters(gas_pipelines=True)
> 
> File "/home/student/git/eTraGo/etrago/tools/plot.py", line 2051, in plot_clusters pipelines = gpd.GeoDataFrame(pipelines, geometry="geom")
> 
> File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/geodataframe.py", line 188, in **init** self.set_geometry(geometry, inplace=True, crs=crs)
> 
> File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/geodataframe.py", line 346, in set_geometry level = _ensure_geometry(level, crs=crs)
> 
> File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/geodataframe.py", line 59, in _ensure_geometry out = from_shapely(np.asarray(data), crs=crs)
> 
> File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/array.py", line 154, in from_shapely return GeometryArray(vectorized.from_shapely(data), crs=crs)
> 
> File "/home/student/venv/etrago_env8/lib/python3.8/site-packages/geopandas/_vectorized.py", line 145, in from_shapely raise TypeError("Input must be valid geometry objects: {0}".format(geom))
> 
> TypeError: Input must be valid geometry objects: MULTILINESTRING ((9.285375 54.803584, 9.29062 54.64853), (9.29062 54.64853, 9.295828 54.49347), (9.295828 54.49347, 9.326504 54.45439), (9.326504 54.45439, 9.315207 54.381631), (9.315207 54.381631, 9.422704 54.264688), (9.422704 54.264688, 9.369836 54.153612))

Updated plot.py with resp. lines.

**Review by CarlosEpia — APPROVED** [review]
LGTM. The problem when importing the etrago object was solved. I updated a couple of default parameters in the description (I hope you don't mind). This branch can be merged into dev.

**Pull request merged**
