### PR TITLE
Pull feature/network variances into dev

### PR DESCRIPTION
**Pull request by ClaraBuettner**
I just changed the import direction to clean up the appl.py. The import and additional settings are now located in nep.py in etrago/tools.
In addition, I changed the line_loading plot so it includes links and added a new plot to show line_extension. 

This branch needs ego.io branch feature/network_variances, for importing extension_tables.

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
I just pushed the branch including the capital_cost calculation.

**Comment by ulfmueller** [comment]
So the PR is ready for review you would say? I can test and merge it tomorrow...

**Comment by ClaraBuettner** [comment]
Everything I tested worked well and I added every feature I might need. So I would say it is ready to review.

**Comment by ulfmueller** [comment]
@ClaraBuettner I can close this PR because of the newer PR #143 , correct?!

**Comment by ClaraBuettner** [comment]
Yes, it's not needed anymore.

**Pull request closed without merging**
