### PR TITLE
Feature/lopf iterations

### PR DESCRIPTION
**Pull request by ClaraBuettner**

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
I just pushed the changes we talked about: 
- line extension of the previous lopf is not set for the next iteration anymore
- maximum extension of each line/trafo ascends with iterations

**Comment by ulfmueller** [comment]
looks fine. Just one aspect I would change. The max_ext I would keep line (component i.e. also transformer) specific, so if you just want to limit a few lines e.g. the cross-border lines only they would be effected instead of taking a mean over all lines...

**Comment by ClaraBuettner** [comment]
In [this branch](https://github.com/openego/eTraGo/tree/feature/lopf_iterations_threshold) I added the possibility to choose if using a fixed number of iteration or a threshold.

**Comment by ulfmueller** [comment]
Nice, can you make a PR from that branch to merge it into this one and add some documentation to the new functionality in the modified method?

**Comment by ClaraBuettner** [comment]
This branch now includes iteration with threshold and model_formulation parameter in args

**Pull request merged**
