### PR TITLE
Features/#301 segmentation for dev

### PR DESCRIPTION
**Pull request by AmeliaNadal**
Implementation of adjacent snapshotclustering

### CODE REVIEW

**Review by KathiEsterl — APPROVED** [review]

**Comment by KathiEsterl** [comment]
Thank you! :)

**Comment by CarlosEpia** [comment]
Hello Amelia and Kathi,
I tried to run dev but it was not successful. Did you test dev after merging? I came back provisionally to the the commit a45fba1d874b0c59a61e9cf37e93af17df8d1443 which is working for me.
`
  File "/home/student/git/eTraGo/etrago/appl.py", line 381, in <module>
    etrago = run_etrago(args, json_path=None)

  File "/home/student/git/eTraGo/etrago/appl.py", line 357, in run_etrago
    etrago.snapshot_clustering()

  File "/home/student/git/eTraGo/etrago/cluster/snapshot.py", line 63, in snapshot_clustering
    how=self.args['snapshot_clustering']['how']

  File "/home/student/git/eTraGo/etrago/cluster/snapshot.py", line 267, in run
    segm_hoursperperiod = network.snapshots.size)

  File "/home/student/git/eTraGo/etrago/cluster/snapshot.py", line 131, in tsam_cluster
    noSegments = segment_no)

TypeError: __init__() got an unexpected keyword argument 'segmentation'`

**Comment by KathiEsterl** [comment]
> Hello Amelia and Kathi, I tried to run dev but it was not successful. Did you test dev after merging? I came back provisionally to the the commit [a45fba1](https://github.com/openego/eTraGo/commit/a45fba1d874b0c59a61e9cf37e93af17df8d1443) which is working for me. ` File "/home/student/git/eTraGo/etrago/appl.py", line 381, in etrago = run_etrago(args, json_path=None)
> 
> File "/home/student/git/eTraGo/etrago/appl.py", line 357, in run_etrago etrago.snapshot_clustering()
> 
> File "/home/student/git/eTraGo/etrago/cluster/snapshot.py", line 63, in snapshot_clustering how=self.args['snapshot_clustering']['how']
> 
> File "/home/student/git/eTraGo/etrago/cluster/snapshot.py", line 267, in run segm_hoursperperiod = network.snapshots.size)
> 
> File "/home/student/git/eTraGo/etrago/cluster/snapshot.py", line 131, in tsam_cluster noSegments = segment_no)
> 
> TypeError: **init**() got an unexpected keyword argument 'segmentation'`

Sorry, I didnt get you commented on Github and answered per e-mail to a wrong mail address. 
However, if anyone else runs into problems like this: We need a new package version of tsam: 1.1.0

**Comment by CarlosEpia** [comment]
Thanks Kathi. That problem is solved.

**Pull request merged**
