### PR TITLE
consider s_nom_min when calculating s_nom_max for transformers

### LINKED ISSUE #478: s_nom_min greater than s_nom_max in some transformers
When calculating the s_nom_max for transformers, there are some cases when s_nom_min is greater than s_nom_max. The function where s_nom_max is calculated was checked and it actually makes sense, but it ignores completely the value in s_nom_min. It leads to infeasibility when running optimizations.

### PR DESCRIPTION
**Pull request by CarlosEpia**
Fix #478.

### CODE REVIEW

**Comment by CarlosEpia** [comment]
@ClaraBuettner these changes just guarantee that s_nom_min is <= s_nom_max. It is possible that some changes are needed to improve the calculation of s_nom_min (or not), but they should be developed in eGon-data.

**Comment by ClaraBuettner** [comment]
I had a brief look at osmtgmod which sets the initial values for s_nom / s_nom_min. It seems like it selected the maximum sum of incoming / outgoing lines at the corresponding buses. So it seems to be reasonable that it is sometimes bigger than the s_nom_max calculated here. 
Could you maybe add a short comment before your additional line of code to explain what you do?

**Comment by CarlosEpia** [comment]
I just added some comments to explain briefly the procedure to calculate the max capacity and the new line to avoid the problem described in #478

**Review by ClaraBuettner — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
