### PR TITLE
gas generators switch and generators scale down

### PR DESCRIPTION
**Pull request by ulfmueller**
- adding gas generators if carrier CH4 is dropped. 
- scaling down the generator capacities (RE) with respect to NEP if all non-AC sectors are dropped.

### CODE REVIEW

**Comment by KathiEsterl** [comment]
When working with the drop_sectors-function, I noticed it might help to automatically disable the gas clustering and the gas constraints when dropping the gas sector. So I added this and merged dev.

**Comment by KathiEsterl** [comment]
When working with the drop_sectors-function, I noticed it might help to automatically disable the gas clustering and the gas constraints when dropping the gas sector. So I added this and merged dev.

**Comment by KathiEsterl** [comment]
Probably this one is not an essential feature for the release, however it is nice to have and already done, so maybe we can also merge that before our deadline. Who would like to review? @ClaraBuettner @CarlosEpia @pieterhexen ?

**Comment by pieterhexen** [comment]
> Probably this one is not an essential feature for the release, however it is nice to have and already done, so maybe we can also merge that before our deadline. Who would like to review? @ClaraBuettner @CarlosEpia @pieterhexen ?

Hey Kathi,

I had a look into the code making generators out of the CH4 to AC links and got the following error when using `etrago.drop_sectors(['CH4'])`:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\etrago\etrago\tools\utilities.py", line 2361, in drop_sectors
    self.network.generators = self.network.generators.append(
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\frame.py", line 9765, in append
    return self._append(other, ignore_index, verify_integrity, sort)
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\frame.py", line 9805, in _append
    result = concat(
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 368, in concat
    op = _Concatenator(
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 563, in __init__
    self.new_axes = self._get_new_axes()
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 633, in _get_new_axes
    return [
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 634, in <listcomp>
    self._get_concat_axis if i == self.bm_axis else self._get_comb_axis(i)
  File "pandas\_libs\properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 697, in _get_concat_axis
    self._maybe_check_integrity(concat_axis)
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 705, in _maybe_check_integrity
    raise ValueError(f"Indexes have overlapping values: {overlap}")
ValueError: Indexes have overlapping values: Index(['37672', '37673', '37674', '37675', '37676', '37677', '37678', '37679',
       '37680', '37681',
       ...
       '47211', '47212', '47213', '47214', '47215', '47216', '47217', '47218',
       '47219', '47220'],
      dtype='object', name='name', length=3207)
`

I used the method right before `etrago.spatial_clustering()`.

It also looks like the automated checks have failed because of `black` / `isort`

**Comment by KathiEsterl** [comment]
> > Probably this one is not an essential feature for the release, however it is nice to have and already done, so maybe we can also merge that before our deadline. Who would like to review? @ClaraBuettner @CarlosEpia @pieterhexen ?
> 
> Hey @KathiEsterl ,
> 
> I had a look into the code making generators out of the CH4 to AC links and got the following error when using `etrago.drop_sectors(['CH4'])`:
> 
> Traceback (most recent call last): File "", line 1, in File "d:\etrago\etrago\tools\utilities.py", line 2361, in drop_sectors self.network.generators = self.network.generators.append( File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\frame.py", line 9765, in append return self._append(other, ignore_index, verify_integrity, sort) File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\frame.py", line 9805, in _append result = concat( File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\util_decorators.py", line 331, in wrapper return func(*args, **kwargs) File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 368, in concat op = _Concatenator( File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 563, in **init** self.new_axes = self._get_new_axes() File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 633, in _get_new_axes return [ File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 634, in self._get_concat_axis if i == self.bm_axis else self._get_comb_axis(i) File "pandas_libs\properties.pyx", line 36, in pandas._libs.properties.CachedProperty.**get** File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 697, in _get_concat_axis self._maybe_check_integrity(concat_axis) File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pandas\core\reshape\concat.py", line 705, in _maybe_check_integrity raise ValueError(f"Indexes have overlapping values: {overlap}") ValueError: Indexes have overlapping values: Index(['37672', '37673', '37674', '37675', '37676', '37677', '37678', '37679', '37680', '37681', ... '47211', '47212', '47213', '47214', '47215', '47216', '47217', '47218', '47219', '47220'], dtype='object', name='name', length=3207) `
> 
> I used the method right before `etrago.spatial_clustering()`.
> 
> It also looks like the automated checks have failed because of `black` / `isort`

Okay, I tried several options and everything worked out in my case. 
However, I improved the way the new generators are added to the network. 
Maybe you can give it another go?

**Review by pieterhexen — APPROVED** [review]

**Pull request merged**
