### PR TITLE
Change installation requirements

### PR DESCRIPTION
**Pull request by ClaraBuettner**
This branch contains needed updates of etragos installation requirements:
- egoio is upgraded to 0.4.7 due to installation problems of 0.4.5 and 0.4.6
- pypsa fork is installed without 'dependency_links' which is not possible with pip>=0.19.0 (see #286)
- pypsa fork of version 0.11.0 doesn't have version-specific requirements but can't handle newest versions of pyomo and networkx. This could be solved in pypsa fork but I added the requirments in etrago to avoid changes in pypsa fork. I can change this there if you prefer that. 
- SQLAlchemy is changed to version 1.2.0 to meet the requirements of eGo and egoio

Before this change, I checked which SQLAlchemy-functions are used in etrago. 
The sessionmaker is used to connect to the database: 
https://github.com/openego/eTraGo/blob/ad176a3a6802c1c2989076e01ed513ff2c3dc6bc/etrago/appl.py#L106
From version 1.1 to 1.2, there is no change in the SQlAlchemy-sessionmaker we use. 
And 'NoResultFound' method is used:
https://github.com/openego/eTraGo/blob/ad176a3a6802c1c2989076e01ed513ff2c3dc6bc/etrago/tools/io.py#L61-L62
This method isn't changed in version 1.2
and_, func, or_ are imported but unused. 
So I'm sure we can update to SQLAlchemy 1.2.

I tested the installation with these requirements in a venv and it went well without any errors or warnings.

### CODE REVIEW

**Comment by ulfmueller** [comment]
I am testing the installation. Unfortunately I get the following error:

    error in eTraGo setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in pypsa @ git+https://github.com/openego/PyPSA.git@master#egg=pypsa-0.11.0fork at  @ git+https://github.com/openego/PyPSA.git@master#egg=pypsa-0.11.0fork

I have no experience with that kind of install_requieres. I used to do it with the dependency links. You don't get that error?

**Comment by ClaraBuettner** [comment]
No, I don't get this error. I installed via `pip install -e /home/clara/GitHub/eTraGo` or is there any other way? 
I have pip version 20.1.1, which one do you have?

**Comment by ulfmueller** [comment]
same installation same pip version...

**Comment by ulfmueller** [comment]
[This](https://github.com/sdispater/pendulum/issues/187#issuecomment-375820769) fixes it.

**Comment by ClaraBuettner** [comment]
I just tested the installation again and it worked without any errors. 
So it's a setuptools version-problem? I remember we once had problems because I have python3.6 and you had 3.5. Could that cause the problem?

**Comment by ulfmueller** [comment]
the installation seems to work fine (although some weird things happened with alchemy but apparently it got installed) but now I get this error when I execute the appl.py

  File "appl.py", line 34, in <module>
    from etrago.tools.utilities import get_args_setting
  File "/home/openego/eTraGo/etrago/tools/utilities.py", line 30, in <module>
    import pypsa
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/pypsa/__init__.py", line 28, in <module>
    from . import components
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/pypsa/components.py", line 37, in <module>
    import scipy as sp, scipy.sparse
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/scipy/fft/__init__.py", line 76, in <module>
    from ._basic import (
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/scipy/_lib/uarray.py", line 27, in <module>
    from ._uarray import *
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/scipy/_lib/_uarray/__init__.py", line 114, in <module>
    from ._backend import *
  File "/home/openego/egon/etrago_test/lib/python3.5/site-packages/scipy/_lib/_uarray/_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'

**Comment by ClaraBuettner** [comment]
From the description of the typing package: 

> NOTE: in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT. To get a newer version of the typing module in Python 3.5 or later, you have to upgrade to a newer Python (bugfix) version. For example, typing in Python 3.6.0 is missing the definition of ‘Type’ – upgrading to 3.6.2 will fix this.

The last sentences seems to cause these problems. Since I have python3.6.9 this bug is fixed in my installation. But I wonder why this did not appear before. These etrago-installation changes don't change the scipy version, but maybe it was updated and didn't use typing package before. I try to check this.

**Comment by ulfmueller** [comment]
I downgraded scipy from version 1.4.1 to 0.18.1 avoiding that error :grimacing:
but I get another one then...

  File "appl.py", line 51, in <module>
    from etrago.cluster.networkclustering import (
  File "/home/openego/eTraGo/etrago/cluster/networkclustering.py", line 27, in <module>
    from pypsa.networkclustering import (aggregatebuses, aggregateoneport,
ImportError: cannot import name 'busmap_by_kmeans'

**Comment by ClaraBuettner** [comment]
Maybe this 'try'-statement doesn't work because of the old scipy-version? 

https://github.com/openego/PyPSA/blob/fd55b9dc3c52648619edd2c6961c584fd4934428/pypsa/networkclustering.py#L395-L404

I can try to install etrago with this branch on the server with python3.5, but I guess I don't have enough permissions for that.

**Comment by ClaraBuettner** [comment]
Can you try to change to these versions: 
scikit-learn==0.19.0
scipy==0.19.0
sklearn==0.0
This works for me and are versions I use on the server with python 3.5

**Comment by ulfmueller** [comment]
nope. still does not work.

**Comment by ClaraBuettner** [comment]
I created a virtual environment using python 3.5 on our server. First I had the same error you have but changing packages to
numpy==1.16.2 and
matplotlib==3.0.3
solved the errors. I installed and run etrago successfully. Should I add/change these requirements in etrago and pypsafork?

**Comment by ulfmueller** [comment]
works very well!

**Comment by ulfmueller** [comment]
I was a bit fast. @ClaraBuettner  Do you want to change the pypsafork dependency directly on the dev branch?

**Comment by ClaraBuettner** [comment]
Yes, I'll do that

**Pull request merged**
