### PR TITLE
Make cartopy dependency optional

### PR DESCRIPTION
**Pull request by fwitte**
BTW:

Within a conda installation of python, pip messes stuff up with conda, <del>my solution was to create a clean environment and then</del>

Edit: Solution did not work...

### CODE REVIEW

**Comment by fwitte** [comment]
Anybody ever gotten this error message:

```
/home/witt_fa/miniforge3/envs/etrago_test/lib/python3.8/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6                                                                                                                       in_crs_string = _prepare_from_proj_string(in_crs_string)                                                                                                                                                                                   /home/witt_fa/miniforge3/envs/etrago_test/lib/python3.8/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6                                                                                                                       in_crs_string = _prepare_from_proj_string(in_crs_string)                                                                                                                                                                                   /home/witt_fa/miniforge3/envs/etrago_test/lib/python3.8/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6                                                                                                                       in_crs_string = _prepare_from_proj_string(in_crs_string)                                                                                                                                                                                   /home/witt_fa/miniforge3/envs/etrago_test/lib/python3.8/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6                                                                                                                       in_crs_string = _prepare_from_proj_string(in_crs_string)                                                                                                                                                                                   Traceback (most recent call last):                                                                                                                                                                                                             File "etrago/appl.py", line 45, in <module>                                                                                                                                                                                                    from etrago import Etrago                                                                                                                                                                                                                  File "/home/witt_fa/eGon/eTraGo/etrago/__init__.py", line 15, in <module>                                                                                                                                                                      from etrago.tools.network import Etrago                                                                                                                                                                                                    File "/home/witt_fa/eGon/eTraGo/etrago/tools/network.py", line 52, in <module>                                                                                                                                                                 from etrago.tools.plot import plot_grid                                                                                                                                                                                                    File "/home/witt_fa/eGon/eTraGo/etrago/tools/plot.py", line 35, in <module>                                                                                                                                                                    import cartopy                                                                                                                                                                                                                             File "/home/witt_fa/miniforge3/envs/etrago_test/lib/python3.8/site-packages/cartopy/__init__.py", line 104, in <module>                                                                                                                        import cartopy.crs                                                                                                                                                                                                                         File "/home/witt_fa/miniforge3/envs/etrago_test/lib/python3.8/site-packages/cartopy/crs.py", line 22, in <module>                                                                                                                              from cartopy._crs import (CRS, Geodetic, Globe, PROJ4_VERSION,                                                                                                                                                                           ImportError: /home/witt_fa/miniforge3/envs/etrago_test/lib/python3.8/site-packages/cartopy/_crs.cpython-38-x86_64-linux-gnu.so: undefined symbol: pj_get_release                                                                             
```

**Comment by ClaraBuettner** [comment]
Could you try to install `cartopy==0.18.0` and the following system-wide packages: 

```
sudo apt-get install python3.7-dev
sudo apt install libproj-dev
sudo apt install libgeos-dev
```

**Comment by fwitte** [comment]
@ClaraBuettner: Can you check, whether the changes work as intended?

**Comment by ClaraBuettner** [comment]
This feature was already implemented by another branch

**Pull request closed without merging**
