### PR TITLE
Solve problem while clustering foreign buses

### PR DESCRIPTION
**Pull request by CarlosEpia**
solves #541

### CODE REVIEW

**Comment by CarlosEpia** [comment]
This branch fixes the problem related to foreign buses clustered to German buses
image

**Comment by CarlosEpia** [comment]
The problem with AC buses is also solved.
image

**Comment by KathiEsterl** [comment]
I would take over the reviewing of this PR :)

**Comment by pieterhexen** [comment]
> I would take over the reviewing of this PR :)

Great! I already applied the code in another branch and found that some 'DE' buses are isolated when only considering the German grid. What happend is that 'DE'-buses only connected through foreign nodes to the German grid are then isolated. The relevant bus-ids I found are '32461' and '33515'. The following image shows the initial state of bus '33515' at the DE/AT border:
grafik

I only applied the method form this PR after doing some other aggregation so it is possible, that the problem is tied to the the things I did. But maybe this serves as a hint for you on where to look a bit closer :)

**Pull request merged**
