### PR TITLE
Fixes/#89

### PR DESCRIPTION
**Pull request by s3pp**
Do you have any way of testing this? As you can see I changed the init method call for ScenarioBase

#89

### CODE REVIEW

**Comment by ulfmueller** [comment]
@wolfbunke can you give your review? If it is good, I could include this in the release...

**Comment by wolfbunke** [comment]
how should /can I test it?

**Comment by s3pp** [comment]
Hmm, without tests in place, I think it's easiest to switch to this branch and run eTraGo on a setup / configuration that is known to work and see what happens : ).

**Comment by ulfmueller** [comment]
@wolfbunke What's up? Have you checked it so we can approve and move on...

**Comment by wolfbunke** [comment]
not yet, try to do it after our call today.

**Comment by wolfbunke** [comment]
I checked it and with a fresh installation. First, tsam was missing as well I got an error due to ego.io see #156. Later I will check all main functions.

**Comment by wolfbunke** [comment]
Running different settings I got following warnings and errors:
```
Traceback (most recent call last):
  File "appl.py", line 400, in <module>
    network = etrago(args)
  File "appl.py", line 352, in etrago
    network.lopf(network.snapshots, solver_name=args['solver'], extra_functionality=extra_functionality)
UnboundLocalError: local variable 'extra_functionality' referenced before assignment

```

and 
```
  File "/home/dozeumbuw/etrago_fix89/lib/python3.5/site-packages/sklearn/base.py", line 411, in fit_predict
    self.fit(X)
  File "/home/dozeumbuw/etrago_fix89/lib/python3.5/site-packages/sklearn/cluster/hierarchical.py", line 695, in fit
    X = check_array(X, ensure_min_samples=2, estimator=self)
  File "/home/dozeumbuw/etrago_fix89/lib/python3.5/site-packages/sklearn/utils/validation.py", line 431, in check_array
    context))
ValueError: Found array with 1 sample(s) (shape=(1, 936)) while a minimum of 2 is required by AgglomerativeClustering.
```

Looks like old and known errors / wrong settings which are already fixed or? @ulfmueller

**Comment by wolfbunke** [comment]
After the update and the single installation of pypsa/dev and ego.io/dev the most function works except  the plotting func. extension_overlay_network(network). 

log:
 ``` python3 appl.py 
/home/dozeumbuw/etrago_fixtest/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO:keyring.backend:Loading SecretService
INFO:keyring.backend:Loading kwallet
INFO:keyring.backend:Loading macOS
INFO:keyring.backend:Loading windows
INFO:keyring.backend:Loading Gnome
INFO:keyring.backend:Loading Google
INFO:keyring.backend:Loading Windows (alt)
INFO:keyring.backend:Loading file
INFO:keyring.backend:Loading keyczar
INFO:keyring.backend:Loading multi
INFO:keyring.backend:Loading pyfs
2018-06-21 15:30:27.942930
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
start k-mean clustering
INFO:pypsa.pf:Slack bus for sub-network 0 is 0
INFO:pypsa.opf:Performed preliminary steps
INFO:pypsa.opf:Building pyomo model using `angles` formulation
INFO:pypsa.opf:Solving model using gurobi
INFO:pypsa.opf:Optimization successful
Time for LOPF [min]: 0.01
Investment costs for all storages in selected snapshots [EUR]: 0.0
2018-06-21 15:31:04.188564
0.048774778842926025
Traceback (most recent call last):
  File "appl.py", line 421, in <module>
    extension_overlay_network(network)
  File "/home/dozeumbuw/etrago_fixtest/eTraGo/etrago/tools/plot.py", line 296, in extension_overlay_network
    cb = plt.colorbar(ll[1], boundaries=v,
IndexError: tuple index out of range

```
Later I will test the results from dev and this branch

**Pull request merged**
