### PR TITLE
Change structure to oop and update pypsa version

### PR DESCRIPTION
**Pull request by ClaraBuettner**
This branch includes several changes. 
First, pypsa was updated to the newest version 0.17.1. According to this, a lot of other packages (like pandas, pyomo...) are also updated to the latest version. 
Some changes in the kmeans-clustering in etrago now allow to use this pypsa version directly, the fork is not needed anymore (described in issue #101).

In addition, the structure in etrago is changed in order to use more object-oriented programming. 
There is a new class Etrago, describing the etrago object which mainly consists of a pypsa.Network and the settings in the args. 
All functionalities, like importing data from the oedb, spatial/temporal clustering and the lopf are now part of the Etrago-object. In addition, some plotting functions and a calculation of main results can be applied directly on this object. 
This leads (at least in my mind) to a better overview of the functionalities and the appl.py which consist now of much less code. 
https://github.com/openego/eTraGo/blob/17f2a95a4bfda68fae79d95798b7bf8d5ad01d37/etrago/tools/network.py#L60-L250

I also adjusted the description in the rtd (mainly the installation instructions and the HowToUse). 
Due to installation problems on windows in the past, I thought about removing this section in the rtd or adding the advice to use a virtual machine with ubuntu. But these problems occurred because of old package version which are updated now so I suggest that windows installation will work (better) by now. I'll try to install this branch on windows and adjust the instructions by then. 

Before merging this into the dev-branch I would like to have some more opinions about it, because it includes a lot of changes which also effect the program structure.

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
When updating the rtd I recognized that the only linked example is not working anymore. (see here: https://github.com/openego/eTraGo/blob/feature/oop_aggregation/doc/howToUse.rst#examples-and-tutorial-notebooks) 
I think it would be better to delete this section (since the default settings in the appl.py could be used as an example) or add new running examples that fit to the new version of etrago.

**Review by wheitkoetter — APPROVED** [review]
As I just started as an etrago developer, I am not able to assess all the changes in-depth. However, I did not find any problems and approve the changes.

**Comment by viole-i** [comment]
I like that we won't need the dependency links anymore.

**Comment by viole-i** [comment]
Like Wilko, I am quite new to eTraGo. I could not find any bugs while installing the new version or running it. Approved from my side.

**Comment by viole-i** [comment]
Accidentally closed, sorry.

**Review by viole-i — APPROVED** [review]

**Comment by ClaraBuettner** [comment]
I just tried to install this eTraGo branch on one of our servers in Flensburg which still uses python 3.5. The installation works but running etrago throws errors because pypsa is only compatible to python 3.6 or 3.7 since version 0.16.0 (e.g. f-strings are used which were added to the python syntax in version 3.6). In general, it is possible to change all these functions, but be would need a pypsa-fork and a lot of time for the adjustments. 
In addition, when using python 3.5 I recently get warnings:
 `DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.`
I think it might be the best option to loose the support for python 3.5 like pypsa. But that means that we need to update our servers. Which version do you use @wheitkoetter @viole-i ?

**Review by ulfmueller — APPROVED** [review]

**Pull request merged**
