### PR TITLE
Fix bug with too many clusters within k-medoids Dijkstra Clustering

### PR DESCRIPTION
**Pull request by KathiEsterl**
Set minimal weighting for spatial clustering and simplify identification of medoid per cluster in k-medoids Dijkstra Clustering

### CODE REVIEW

**Review by CarlosEpia — APPROVED** [review]
Looks good to me. This branch can be merged.

**Comment by KathiEsterl** [comment]
I added the query to set the cores for the multiprocessing. 

@CarlosEpia Maybe you want to have another look and give me a sign, then I will merge this branch. 

Thank you!

**Review by CarlosEpia — APPROVED** [review]
It looks good to me. Do you think that it could be useful to include in the message the maximum possible number of cores? Something like "cpu_cores (default 4, max {mp.cpu_count()}): "

**Comment by KathiEsterl** [comment]
> It looks good to me. Do you think that it could be useful to include in the message the maximum possible number of cores? Something like "cpu_cores (default 4, max {mp.cpu_count()}): "

I added this option. Thank you!

**Pull request merged**
